<div class="right_cnn">
<table width="300" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="35" colspan="2" bgcolor="#f6f6f6"><h3>24小时新闻11</h3><span><a href="#">更多>></a></span></td>
    </tr>
  <tr>
    <td width="40" height="55" align="center"><strong>16:53</strong></td>
    <td width="260" height="58" align="left" valign="middle"><p><a href="#">对于网络曝光的相关问题，张少龙介绍通过网络曝光</a></p></td>
  </tr>
  <tr>
      <td width="40" height="55" align="center"><strong>15:50</strong></td>
    <td width="260" height="58" valign="middle"><p><a href="#">对于网络曝光的相关问题，张少龙介绍通过网络曝光</a></p></td>
  </tr>
  <tr>
     <td width="40" height="55" align="center"><strong>15:35</strong></td>
    <td width="260" height="58" valign="middle"><p><a href="#">对于网络曝光的相关问题，张少</a></p></td>
  </tr>
</table>
</div>
<div class="index_blank"></div>